//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventorydbEntities : DbContext
    {
        public inventorydbEntities()
            : base("name=inventorydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vw_Users> Vw_Users { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Vw_Customer> Vw_Customer { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Vw_Product> Vw_Product { get; set; }
        public virtual DbSet<ProductPrice> ProductPrices { get; set; }
        public virtual DbSet<Vw_ProductPrice> Vw_ProductPrice { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Vw_Inventory> Vw_Inventory { get; set; }
    }
}
